name: bazaarniti
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  double_back_to_close: ^2.0.0
  file_picker: ^5.2.6
  flutter_html: ^3.0.0-alpha.6
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  image_picker: ^0.8.7
  intl: ^0.18.0
  lottie: ^2.3.0
  onesignal_flutter: ^3.5.1
  path: ^1.8.2
  path_provider: ^2.0.14
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  upgrader: ^6.2.0
  url_launcher: ^6.1.10
  validators: ^3.0.0
  animated_bottom_navigation_bar: ^1.2.0
  jiffy: ^6.2.1
  pusher_channels_flutter: ^2.1.2
  flutterx_live_data: ^1.8.9
  timeline_list: ^0.0.6
  dropdown_search: ^5.0.6
  http: ^0.13.5
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/app_logo.png"
  ios: true
  remove_alpha_ios: true
  #flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  background_image: "assets/splash.png"
  android: true
  ios: true
  #flutter pub run flutter_native_splash:create

flutter:
  fonts:
    - family: Regular
      fonts:
        - asset: fonts/poppins_regular.ttf
    - family: Medium
      fonts:
        - asset: fonts/poppins_medium.ttf
    - family: Bold
      fonts:
        - asset: fonts/poppins_semi_bold.ttf
          weight: 500
  uses-material-design: true
  generate: true
  assets:
    - assets/